[package]
name = "ld46"
version = "0.1.0"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
license = "AGPL-3.0-or-later"
edition = "2018"
readme = "README.md"
repository = "https://github.com/tversteeg/ld46"
documentation = "https://docs.rs/ld46"
description = ""
keywords = []
categories = []

[badges]
is-it-maintained-issue-resolution = { repository = "tversteeg/ld46" }
is-it-maintained-open-issues = { repository = "tversteeg/ld46" }

[features]
default = []
parallel = ["specs-blit/parallel"]

[dependencies]
anyhow = "1.0.28"
derive_deref = "1.1.0"
lazy_static = "1.4.0"
#const-tweaker = "0.3.1"
#cpal = "0.11.0"
miniquad = "0.2.54"
specs-blit = { version = "0.4.3", default-features = false }
sprite-gen = "0.2.0"
usfx = "0.1.3"
vek = "0.10.1"
